import{useEffect,useMemo,useState}from"react";import{Plus,Trash2,WalletCards,ArrowDownCircle,ArrowUpCircle,Search,Sun,Moon}from"lucide-react";
type Kind="income"|"expense";type Entry={id:string;kind:Kind;amount:number;category:string;note:string;date:string};
const CATS=["餐饮","交通","购物","娱乐","学习","住房","工资","其他"];const money=(n:number)=>new Intl.NumberFormat("zh-CN",{style:"currency",currency:"CNY"}).format(n);const today=()=>new Date().toISOString().slice(0,10);
export default function App(){const[entries,setEntries]=useState<Entry[]>(()=>JSON.parse(localStorage.getItem("pocket-ledger")||"[]"));const[dark,setDark]=useState(()=>localStorage.getItem("pocket-dark")==="1");const[kind,setKind]=useState<Kind>("expense");const[amount,setAmount]=useState("");const[category,setCategory]=useState("餐饮");const[note,setNote]=useState("");const[date,setDate]=useState(today());const[query,setQuery]=useState("");const[month,setMonth]=useState(today().slice(0,7));
useEffect(()=>localStorage.setItem("pocket-ledger",JSON.stringify(entries)),[entries]);useEffect(()=>{document.documentElement.dataset.theme=dark?"dark":"light";localStorage.setItem("pocket-dark",dark?"1":"0")},[dark]);
const filtered=useMemo(()=>entries.filter(e=>e.date.startsWith(month)&&(e.note+e.category).toLowerCase().includes(query.toLowerCase())).sort((a,b)=>b.date.localeCompare(a.date)),[entries,month,query]);const income=filtered.filter(e=>e.kind==="income").reduce((s,e)=>s+e.amount,0);const expense=filtered.filter(e=>e.kind==="expense").reduce((s,e)=>s+e.amount,0);
const add=()=>{const n=Number(amount);if(!n||n<0)return;setEntries([{id:crypto.randomUUID(),kind,amount:n,category,note:note.trim()||category,date},...entries]);setAmount("");setNote("")};const remove=(id:string)=>setEntries(entries.filter(e=>e.id!==id));
return <main><header><div className="brand"><WalletCards size={28}/><div><h1>Pocket Ledger</h1><span>把钱花明白，也把生活记下来。</span></div></div><button className="icon" onClick={()=>setDark(!dark)}>{dark?<Sun/>:<Moon/>}</button></header>
<section className="hero"><div><small>本月结余</small><strong>{money(income-expense)}</strong></div><div className="heroStats"><span>收入<b>{money(income)}</b></span><span>支出<b>{money(expense)}</b></span></div></section>
<section className="card form"><div className="seg"><button className={kind==="expense"?"active":""} onClick={()=>setKind("expense")}>支出</button><button className={kind==="income"?"active income":""} onClick={()=>setKind("income")}>收入</button></div>
<div className="grid"><label>金额<input inputMode="decimal" placeholder="0.00" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>日期<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>分类<select value={category} onChange={e=>setCategory(e.target.value)}>{CATS.map(c=><option key={c}>{c}</option>)}</select></label><label>备注<input placeholder="今天为什么花这笔？" value={note} onChange={e=>setNote(e.target.value)}/></label></div><button className="add" onClick={add}><Plus size={19}/>记一笔</button></section>
<div className="toolbar"><label>月份<input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label><label className="search"><Search size={17}/><input placeholder="搜索分类或备注" value={query} onChange={e=>setQuery(e.target.value)}/></label></div>
<section className="list">{filtered.length===0?<div className="empty">还没有记录。<br/><span>从一笔小小的记账开始。</span></div>:filtered.map(e=><article className="entry" key={e.id}><div className={"bubble "+e.kind}>{e.kind==="income"?<ArrowUpCircle/>:<ArrowDownCircle/>}</div><div className="desc"><b>{e.note||e.category}</b><span>{e.category} · {e.date}</span></div><strong className={e.kind}>{e.kind==="income"?"+":"−"}{money(e.amount)}</strong><button className="delete" onClick={()=>remove(e.id)}><Trash2 size={16}/></button></article>)}</section><footer>数据只保存在你的浏览器里 · Pocket Ledger</footer></main>}